apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  type: NodePort
  selector:
    app: node-red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
